name: Make docs

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths: 
    - 'drhook/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Install latexmk
      run: sudo apt install -y latexmk

    - name: Make html
      run: make -C drhook html

    - name: Make pdf
      run: make -C drhook latexpdf

    - name: Make md
      run: make -C drhook markdown
