name: Make docs

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths: 
    - 'drhook/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # Caching pip dependencies
    - uses: awalsh128/cache-apt-pkgs-action@v1.4.3
      with:
        packages: latexmk texlive-latex-extra # Caching apt dependencies
        execute_install_scripts: true
    - run: pip install -r requirements.txt

    - name: Make html
      run: make -C drhook html

    - name: Make pdf
      run: make -C drhook latexpdf

    - name: Make md
      run: make -C drhook markdown

    - name: Check diff
      # Don't check latexpdf or drhook/_build/html as they contain version hashes etc
      # They get rebuilt as part of cd, so just a ci check that they're not broken is fine
      run: git diff --exit-code  -- drhook/_build/markdown
